### ISSUE TITLE
CORS exception for leafletImage on localhost

### ISSUE THREAD

**Issue by mobidev111** [mapbox/leaflet-image#31]
I get a CORS error on localhost using standard mapbox initialisation. Any directions on how to resolve this?

``` javascript
        map = L.mapbox.map('map', 'user_id.map_id');
        leafletImage(map, function(err, canvas) {
            // process image here
        })
```

```
Image from origin 'http://api.tiles.mapbox.com' has been blocked from loading by Cross-Origin Resource Sharing policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Origin 'http://localhost:8000' is therefore not allowed access.
```

**Comment by jfirebaugh** [comment]
What's the full URL of the resource that's producing that error?

**Comment by mobidev111** [comment]
Don't know. How can I find out about the exact URL causing this?

The error appears in Chrome Desktop. No other console output.

I added mapbox with "L.mapbox.map('map', 'user_id.map_id');" It is a plain map, nothing added or so.

**Comment by mobidev111** [comment]
@jfirebaugh Any hints on this?

**Comment by jfirebaugh** [comment]
@mobidev111 Do you have a proxy or firewall on your internet connection? The "The 'Access-Control-Allow-Origin' header contains multiple values '*, *'" error suggests that something is rewriting the response from Mapbox. You could try setting `L.mapbox.config.FORCE_HTTPS = true;` so that the connection is encrypted.
